### ISSUE TITLE
Broken link + suggestions

### ISSUE THREAD

**Issue by elblan** [factorlive/fbmessenger-pywebhook#3]
Hi,

First, thanks for sharing your implementation, very useful! 

A few comments: 

- The introduction video link leads to a 404
- The regex for the verification challenge resulted in a 422 when trying to verify my integration from Facebook. Overall, I think validation is unnecessary here, for the verification token too for example as it is user generated and could contain any character.
- The `FB_PAGE` environment variable can be confusing. At first, I thought this was used for the Facebook Page ID but it is actually for the Page access token. I would suggest to rename it to `FB_PAGE_ACCESS_TOKEN` or something more reflective of its purpose. 
- I had to look for additional resources to set up my application and the webhook, [this one](https://developers.facebook.com/docs/messenger-platform/getting-started/app-setup) was particularly useful. I think it would be a good addition to the readme.

**Comment by factorlive** [comment]
Thank you for the hint and the suggestions. I am glad that you could still fix the 422 response error. The regex is still there but the response model bug is gone as I reverted to use directly starlette. The regex is rather restrictive, however the instructions of FB developer do specify how the challenge would look like. 

Thanks also for the other suggestions. All of them are in the README now. I also added a CHANGES file.
